//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.6
//
// <auto-generated>
//
// Generated from file `io_channel_ice.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

#include <io_channel_ice.h>
#include <IceUtil/PushDisableWarnings.h>
#include <Ice/LocalException.h>
#include <Ice/ValueFactory.h>
#include <Ice/OutgoingAsync.h>
#include <Ice/InputStream.h>
#include <Ice/OutputStream.h>
#include <Ice/LocalException.h>
#include <IceUtil/PopDisableWarnings.h>

#if defined(_MSC_VER)
#   pragma warning(disable:4458) // declaration of ... hides class member
#elif defined(__clang__)
#   pragma clang diagnostic ignored "-Wshadow"
#elif defined(__GNUC__)
#   pragma GCC diagnostic ignored "-Wshadow"
#endif

#ifndef ICE_IGNORE_VERSION
#   if ICE_INT_VERSION / 100 != 307
#       error Ice version mismatch!
#   endif
#   if ICE_INT_VERSION % 100 >= 50
#       error Beta header file detected
#   endif
#   if ICE_INT_VERSION % 100 < 6
#       error Ice patch level mismatch!
#   endif
#endif

#ifdef ICE_CPP11_MAPPING // C++11 mapping

namespace
{

const ::IceInternal::DefaultUserExceptionFactoryInit<::ChannelSdk::SendDataException> iceC_ChannelSdk_SendDataException_init("::ChannelSdk::SendDataException");

const ::std::string iceC_ChannelSdk_IoChannel_ids[2] =
{
    "::ChannelSdk::IoChannel",
    "::Ice::Object"
};
const ::std::string iceC_ChannelSdk_IoChannel_ops[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "send"
};
const ::std::string iceC_ChannelSdk_IoChannel_send_name = "send";

}

ChannelSdk::SendDataException::~SendDataException()
{
}

const ::std::string&
ChannelSdk::SendDataException::ice_staticId()
{
    static const ::std::string typeId = "::ChannelSdk::SendDataException";
    return typeId;
}

bool
ChannelSdk::IoChannel::ice_isA(::std::string s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_ChannelSdk_IoChannel_ids, iceC_ChannelSdk_IoChannel_ids + 2, s);
}

::std::vector<::std::string>
ChannelSdk::IoChannel::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector<::std::string>(&iceC_ChannelSdk_IoChannel_ids[0], &iceC_ChannelSdk_IoChannel_ids[2]);
}

::std::string
ChannelSdk::IoChannel::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
ChannelSdk::IoChannel::ice_staticId()
{
    static const ::std::string typeId = "::ChannelSdk::IoChannel";
    return typeId;
}

/// \cond INTERNAL
bool
ChannelSdk::IoChannel::_iceD_send(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::OperationMode::Idempotent, current.mode);
    auto istr = inS.startReadParams();
    ::std::string iceP_nodeid;
    ::std::string iceP_msgid;
    bytes iceP_data;
    istr->readAll(iceP_nodeid, iceP_msgid, iceP_data);
    inS.endReadParams();
    auto inA = ::IceInternal::IncomingAsync::create(inS);
    auto responseCB = [inA](int ret)
    {
        auto ostr = inA->startWriteParams();
        ostr->writeAll(ret);
        inA->endWriteParams();
        inA->completed();
    };
    this->sendAsync(::std::move(iceP_nodeid), ::std::move(iceP_msgid), ::std::move(iceP_data), responseCB, inA->exception(), current);
    return false;
}
/// \endcond

/// \cond INTERNAL
bool
ChannelSdk::IoChannel::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_ChannelSdk_IoChannel_ops, iceC_ChannelSdk_IoChannel_ops + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_ChannelSdk_IoChannel_ops)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_send(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond INTERNAL
void
ChannelSdk::IoChannelPrx::_iceI_send(const ::std::shared_ptr<::IceInternal::OutgoingAsyncT<int>>& outAsync, const ::std::string& iceP_nodeid, const ::std::string& iceP_msgid, const bytes& iceP_data, const ::Ice::Context& context)
{
    _checkTwowayOnly(iceC_ChannelSdk_IoChannel_send_name);
    outAsync->invoke(iceC_ChannelSdk_IoChannel_send_name, ::Ice::OperationMode::Idempotent, ::Ice::FormatType::DefaultFormat, context,
        [&](::Ice::OutputStream* ostr)
        {
            ostr->writeAll(iceP_nodeid, iceP_msgid, iceP_data);
        },
        [](const ::Ice::UserException& ex)
        {
            try
            {
                ex.ice_throw();
            }
            catch(const SendDataException&)
            {
                throw;
            }
            catch(const ::Ice::UserException&)
            {
            }
        });
}
/// \endcond

/// \cond INTERNAL
::std::shared_ptr<::Ice::ObjectPrx>
ChannelSdk::IoChannelPrx::_newInstance() const
{
    return ::IceInternal::createProxy<IoChannelPrx>();
}
/// \endcond

const ::std::string&
ChannelSdk::IoChannelPrx::ice_staticId()
{
    return IoChannel::ice_staticId();
}

namespace Ice
{
}

#else // C++98 mapping

namespace
{

const ::std::string iceC_ChannelSdk_IoChannel_send_name = "send";

}

namespace
{

const ::IceInternal::DefaultUserExceptionFactoryInit< ::ChannelSdk::SendDataException> iceC_ChannelSdk_SendDataException_init("::ChannelSdk::SendDataException");

}

#ifdef ICE_CPP11_COMPILER
ChannelSdk::SendDataException::~SendDataException()
{
}
#else
ChannelSdk::SendDataException::~SendDataException() throw()
{
}
#endif

::std::string
ChannelSdk::SendDataException::ice_id() const
{
    return "::ChannelSdk::SendDataException";
}

ChannelSdk::SendDataException*
ChannelSdk::SendDataException::ice_clone() const
{
    return new SendDataException(*this);
}

void
ChannelSdk::SendDataException::ice_throw() const
{
    throw *this;
}

/// \cond STREAM
void
ChannelSdk::SendDataException::_writeImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice("::ChannelSdk::SendDataException", -1, true);
    ::Ice::StreamWriter< SendDataException, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
ChannelSdk::SendDataException::_readImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< SendDataException, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

ChannelSdk::AMD_IoChannel_send::~AMD_IoChannel_send()
{
}

/// \cond INTERNAL
IceAsync::ChannelSdk::AMD_IoChannel_send::AMD_IoChannel_send(::IceInternal::Incoming& in) :
    ::IceInternal::IncomingAsync(in)
{
}

void
IceAsync::ChannelSdk::AMD_IoChannel_send::ice_response(::Ice::Int ret)
{
    ::Ice::OutputStream* ostr = startWriteParams();
    ostr->write(ret);
    endWriteParams();
    completed();
}
/// \endcond

/// \cond INTERNAL
::IceProxy::Ice::Object* ::IceProxy::ChannelSdk::upCast(IoChannel* p) { return p; }

void
::IceProxy::ChannelSdk::_readProxy(::Ice::InputStream* istr, ::IceInternal::ProxyHandle< IoChannel>& v)
{
    ::Ice::ObjectPrx proxy;
    istr->read(proxy);
    if(!proxy)
    {
        v = 0;
    }
    else
    {
        v = new IoChannel;
        v->_copyFrom(proxy);
    }
}
/// \endcond

::Ice::AsyncResultPtr
IceProxy::ChannelSdk::IoChannel::_iceI_begin_send(const ::std::string& iceP_nodeid, const ::std::string& iceP_msgid, const ::ChannelSdk::bytes& iceP_data, const ::Ice::Context& context, const ::IceInternal::CallbackBasePtr& del, const ::Ice::LocalObjectPtr& cookie, bool sync)
{
    _checkTwowayOnly(iceC_ChannelSdk_IoChannel_send_name, sync);
    ::IceInternal::OutgoingAsyncPtr result = new ::IceInternal::CallbackOutgoing(this, iceC_ChannelSdk_IoChannel_send_name, del, cookie, sync);
    try
    {
        result->prepare(iceC_ChannelSdk_IoChannel_send_name, ::Ice::Idempotent, context);
        ::Ice::OutputStream* ostr = result->startWriteParams(::Ice::DefaultFormat);
        ostr->write(iceP_nodeid);
        ostr->write(iceP_msgid);
        ostr->write(iceP_data);
        result->endWriteParams();
        result->invoke(iceC_ChannelSdk_IoChannel_send_name);
    }
    catch(const ::Ice::Exception& ex)
    {
        result->abort(ex);
    }
    return result;
}

::Ice::Int
IceProxy::ChannelSdk::IoChannel::end_send(const ::Ice::AsyncResultPtr& result)
{
    ::Ice::AsyncResult::_check(result, this, iceC_ChannelSdk_IoChannel_send_name);
    ::Ice::Int ret;
    if(!result->_waitForResponse())
    {
        try
        {
            result->_throwUserException();
        }
        catch(const ::ChannelSdk::SendDataException&)
        {
            throw;
        }
        catch(const ::Ice::UserException& ex)
        {
            throw ::Ice::UnknownUserException(__FILE__, __LINE__, ex.ice_id());
        }
    }
    ::Ice::InputStream* istr = result->_startReadParams();
    istr->read(ret);
    result->_endReadParams();
    return ret;
}

/// \cond INTERNAL
::IceProxy::Ice::Object*
IceProxy::ChannelSdk::IoChannel::_newInstance() const
{
    return new IoChannel;
}
/// \endcond

const ::std::string&
IceProxy::ChannelSdk::IoChannel::ice_staticId()
{
    return ::ChannelSdk::IoChannel::ice_staticId();
}

ChannelSdk::IoChannel::~IoChannel()
{
}

/// \cond INTERNAL
::Ice::Object* ChannelSdk::upCast(IoChannel* p) { return p; }

/// \endcond

namespace
{
const ::std::string iceC_ChannelSdk_IoChannel_ids[2] =
{
    "::ChannelSdk::IoChannel",
    "::Ice::Object"
};

}

bool
ChannelSdk::IoChannel::ice_isA(const ::std::string& s, const ::Ice::Current&) const
{
    return ::std::binary_search(iceC_ChannelSdk_IoChannel_ids, iceC_ChannelSdk_IoChannel_ids + 2, s);
}

::std::vector< ::std::string>
ChannelSdk::IoChannel::ice_ids(const ::Ice::Current&) const
{
    return ::std::vector< ::std::string>(&iceC_ChannelSdk_IoChannel_ids[0], &iceC_ChannelSdk_IoChannel_ids[2]);
}

const ::std::string&
ChannelSdk::IoChannel::ice_id(const ::Ice::Current&) const
{
    return ice_staticId();
}

const ::std::string&
ChannelSdk::IoChannel::ice_staticId()
{
#ifdef ICE_HAS_THREAD_SAFE_LOCAL_STATIC
    static const ::std::string typeId = "::ChannelSdk::IoChannel";
    return typeId;
#else
    return iceC_ChannelSdk_IoChannel_ids[0];
#endif
}

/// \cond INTERNAL
bool
ChannelSdk::IoChannel::_iceD_send(::IceInternal::Incoming& inS, const ::Ice::Current& current)
{
    _iceCheckMode(::Ice::Idempotent, current.mode);
    ::Ice::InputStream* istr = inS.startReadParams();
    ::std::string iceP_nodeid;
    ::std::string iceP_msgid;
    bytes iceP_data;
    istr->read(iceP_nodeid);
    istr->read(iceP_msgid);
    istr->read(iceP_data);
    inS.endReadParams();
    this->send_async(new IceAsync::ChannelSdk::AMD_IoChannel_send(inS), iceP_nodeid, iceP_msgid, iceP_data, current);
    return false;
}
/// \endcond

namespace
{
const ::std::string iceC_ChannelSdk_IoChannel_all[] =
{
    "ice_id",
    "ice_ids",
    "ice_isA",
    "ice_ping",
    "send"
};

}

/// \cond INTERNAL
bool
ChannelSdk::IoChannel::_iceDispatch(::IceInternal::Incoming& in, const ::Ice::Current& current)
{
    ::std::pair<const ::std::string*, const ::std::string*> r = ::std::equal_range(iceC_ChannelSdk_IoChannel_all, iceC_ChannelSdk_IoChannel_all + 5, current.operation);
    if(r.first == r.second)
    {
        throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
    }

    switch(r.first - iceC_ChannelSdk_IoChannel_all)
    {
        case 0:
        {
            return _iceD_ice_id(in, current);
        }
        case 1:
        {
            return _iceD_ice_ids(in, current);
        }
        case 2:
        {
            return _iceD_ice_isA(in, current);
        }
        case 3:
        {
            return _iceD_ice_ping(in, current);
        }
        case 4:
        {
            return _iceD_send(in, current);
        }
        default:
        {
            assert(false);
            throw ::Ice::OperationNotExistException(__FILE__, __LINE__, current.id, current.facet, current.operation);
        }
    }
}
/// \endcond

/// \cond STREAM
void
ChannelSdk::IoChannel::_iceWriteImpl(::Ice::OutputStream* ostr) const
{
    ostr->startSlice(ice_staticId(), -1, true);
    ::Ice::StreamWriter< IoChannel, ::Ice::OutputStream>::write(ostr, *this);
    ostr->endSlice();
}

void
ChannelSdk::IoChannel::_iceReadImpl(::Ice::InputStream* istr)
{
    istr->startSlice();
    ::Ice::StreamReader< IoChannel, ::Ice::InputStream>::read(istr, *this);
    istr->endSlice();
}
/// \endcond

/// \cond INTERNAL
void
ChannelSdk::_icePatchObjectPtr(IoChannelPtr& handle, const ::Ice::ObjectPtr& v)
{
    handle = IoChannelPtr::dynamicCast(v);
    if(v && !handle)
    {
        IceInternal::Ex::throwUOE(IoChannel::ice_staticId(), v);
    }
}
/// \endcond

namespace Ice
{
}

#endif
