// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: via.proto

#include "via.pb.h"
#include "via.grpc.pb.h"

#include <functional>
#include <grpcpp/impl/codegen/async_stream.h>
#include <grpcpp/impl/codegen/async_unary_call.h>
#include <grpcpp/impl/codegen/channel_interface.h>
#include <grpcpp/impl/codegen/client_unary_call.h>
#include <grpcpp/impl/codegen/client_callback.h>
#include <grpcpp/impl/codegen/message_allocator.h>
#include <grpcpp/impl/codegen/method_handler.h>
#include <grpcpp/impl/codegen/rpc_service_method.h>
#include <grpcpp/impl/codegen/server_callback.h>
#include <grpcpp/impl/codegen/server_callback_handlers.h>
#include <grpcpp/impl/codegen/server_context.h>
#include <grpcpp/impl/codegen/service_type.h>
#include <grpcpp/impl/codegen/sync_stream.h>
namespace via {

static const char* VIAService_method_names[] = {
  "/via.VIAService/Signup",
};

std::unique_ptr< VIAService::Stub> VIAService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< VIAService::Stub> stub(new VIAService::Stub(channel, options));
  return stub;
}

VIAService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Signup_(VIAService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status VIAService::Stub::Signup(::grpc::ClientContext* context, const ::via::SignupReq& request, ::via::Boolean* response) {
  return ::grpc::internal::BlockingUnaryCall< ::via::SignupReq, ::via::Boolean, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Signup_, context, request, response);
}

void VIAService::Stub::async::Signup(::grpc::ClientContext* context, const ::via::SignupReq* request, ::via::Boolean* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::via::SignupReq, ::via::Boolean, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Signup_, context, request, response, std::move(f));
}

void VIAService::Stub::async::Signup(::grpc::ClientContext* context, const ::via::SignupReq* request, ::via::Boolean* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Signup_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::via::Boolean>* VIAService::Stub::PrepareAsyncSignupRaw(::grpc::ClientContext* context, const ::via::SignupReq& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::via::Boolean, ::via::SignupReq, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Signup_, context, request);
}

::grpc::ClientAsyncResponseReader< ::via::Boolean>* VIAService::Stub::AsyncSignupRaw(::grpc::ClientContext* context, const ::via::SignupReq& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncSignupRaw(context, request, cq);
  result->StartCall();
  return result;
}

VIAService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      VIAService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< VIAService::Service, ::via::SignupReq, ::via::Boolean, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](VIAService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::via::SignupReq* req,
             ::via::Boolean* resp) {
               return service->Signup(ctx, req, resp);
             }, this)));
}

VIAService::Service::~Service() {
}

::grpc::Status VIAService::Service::Signup(::grpc::ServerContext* context, const ::via::SignupReq* request, ::via::Boolean* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace via

